Update workflow_automation.yml

diff --git a/.github/workflows/workflow_automation.yml b/.github/workflows/workflow_automation.yml
--- a/.github/workflows/workflow_automation.yml
+++ b/.github/workflows/workflow_automation.yml
@@ -1,33 +1,38 @@
-name: Run Master Pipeline
+name: Run master pipeline
+
+
 on:
   push:
     branches: [ "main" ]
   pull_request:
     branches: [ "main" ]
   workflow_dispatch:
-  
+
 jobs:
-  run-workflow:
+  build:
+
     runs-on: ubuntu-latest
 
     steps:
+    - name: Checkout repository
+      uses: actions/checkout@v4
 
-      - name: Checkout repository
-        uses: actions/checkout@v4
-        
-      - name: Set up Python 3.10
-        uses: actions/setup-python@v3
-        with:
-          python-version: "3.10"
+    - name: Set up Python 3.10
+      uses: actions/setup-python@v3
+      with:
+        python-version: "3.10"
 
+    - name: Install dependencies
+      run: |
+        python -m pip install --upgrade pip
+        pip install pandas requests numpy seaborn matplotlib flake8 pytest
 
-      - name: Install Python dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install pandas requests numpy seaborn matplotlib flake8 pytest
+    - name: Lint with flake8
+      run: |
+        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
+        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
 
-
-      - name: Run workflow.py
-        run: |
-          set -e  # Stop immediately if any command fails
-          python workflow.py
+    - name: Run master workflow
+      run: |
+        set -e  # <-- stops immediately if any subscript fails
+        python workflow.py
